#!/usr/bin/env python3
"""BudgetSense coverage gate.

Reads coverage/lcov.info and enforces two independent, blocking rules:

  1. Overall meaningful line coverage must be >= THRESHOLD (default 70%).
  2. No file in the CRITICAL set may sit at 0% coverage.

"Meaningful" coverage excludes code that is generated or is pure platform /
declarative glue with no runtime-executed logic. Every exclusion is listed
here with a reason so the number is honest and auditable, not gamed.

Usage:
    python3 tool/coverage_report.py [--threshold 70] [--lcov coverage/lcov.info]

Exit code 0 = pass, 1 = fail. Prints a per-layer breakdown either way.
"""
from __future__ import annotations

import argparse
import sys
from collections import defaultdict

# Files excluded from the coverage denominator, each with an explicit reason.
# Matched by suffix against the SF: path.
EXCLUSIONS = {
    ".g.dart": "generated by build_runner/drift (not hand-written logic)",
    "lib/data/database/connection.dart": (
        "platform I/O only: opens the native SQLite file via path_provider and "
        "a background isolate; not reachable in host unit tests"
    ),
    "lib/data/database/tables.dart": (
        "declarative Drift table/column definitions consumed by the code "
        "generator at build time; the runtime schema lives in the generated "
        "*.g.dart, so these getters never execute at runtime"
    ),
    "lib/data/cloud/google_drive_gateway.dart": (
        "device-only: real Google Sign-In (google_sign_in) + Drive API "
        "(googleapis) calls that cannot run without Google auth/network in CI. "
        "Its behavior is covered through the CloudBackupGateway/AuthGateway "
        "interfaces with in-memory fakes and must be verified on device "
        "(docs/backup/GOOGLE_DRIVE_SETUP.md)"
    ),
    "lib/data/updates/update_gateway.dart": (
        "network-only: GitHub Releases HTTP fetch/download. Covered via the "
        "UpdateGateway interface with a fake; not run in CI"
    ),
    "lib/data/updates/apk_installer.dart": (
        "device-only: hands the APK to the Android system installer over a "
        "MethodChannel. Covered via the ApkInstaller interface with a fake"
    ),
}

# Files that must NEVER be at 0% coverage (production-critical infrastructure).
CRITICAL_MARKERS = (
    "lib/data/repositories/",
    "lib/data/snapshot/",
    "lib/data/cloud/cloud_sync_controller.dart",
    "lib/data/cloud/encryption_service.dart",
    "lib/data/cloud/mutation_tracker.dart",
    "lib/data/cloud/cloud_metadata_store.dart",
    "lib/data/updates/update_service.dart",
    "lib/data/updates/update_manifest.dart",
    "lib/data/import/",
    "lib/data/export/",
    "lib/domain/services/",
    "lib/app/providers.dart",
    "lib/app/feature_providers.dart",
    "lib/core/services/",
    "lib/features/settings/settings_controller.dart",
)

LAYERS = {
    "app (DI)": "lib/app/",
    "core": "lib/core/",
    "domain": "lib/domain/",
    "data/repositories": "lib/data/repositories/",
    "data/other": "lib/data/",
    "features": "lib/features/",
}


def excluded(path: str) -> str | None:
    for marker, reason in EXCLUSIONS.items():
        if path.endswith(marker) or marker in path:
            return reason
    return None


def parse_lcov(path: str) -> dict[str, tuple[int, int]]:
    per: dict[str, tuple[int, int]] = {}
    cur = None
    found = hit = 0
    with open(path) as fh:
        for raw in fh:
            line = raw.rstrip("\n")
            if line.startswith("SF:"):
                cur, found, hit = line[3:], 0, 0
            elif line.startswith("DA:"):
                count = int(line.split(",")[1])
                found += 1
                hit += 1 if count > 0 else 0
            elif line == "end_of_record" and cur is not None:
                per[cur] = (hit, found)
                cur = None
    return per


def rel(path: str) -> str:
    return path.split("BudgetSense/", 1)[-1] if "BudgetSense/" in path else path


def layer_of(path: str) -> str:
    r = rel(path)
    # Most specific first.
    if r.startswith("lib/data/repositories/"):
        return "data/repositories"
    for name, marker in LAYERS.items():
        if r.startswith(marker):
            return name
    return "other"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--threshold", type=float, default=70.0)
    ap.add_argument("--lcov", default="coverage/lcov.info")
    args = ap.parse_args()

    try:
        per = parse_lcov(args.lcov)
    except FileNotFoundError:
        print(f"ERROR: {args.lcov} not found. Run: flutter test --coverage")
        return 1

    included = {p: v for p, v in per.items() if not excluded(p)}
    total_hit = sum(h for h, _ in included.values())
    total_found = sum(f for _, f in included.values())
    pct = 100 * total_hit / total_found if total_found else 0.0

    print("BudgetSense coverage gate")
    print("=" * 60)
    print(f"Meaningful line coverage: {pct:.2f}%  ({total_hit}/{total_found})")
    print(f"Threshold:                {args.threshold:.2f}%")
    print()

    # Per-layer breakdown.
    layer_hit: dict[str, int] = defaultdict(int)
    layer_found: dict[str, int] = defaultdict(int)
    for p, (h, f) in included.items():
        lyr = layer_of(p)
        layer_hit[lyr] += h
        layer_found[lyr] += f
    print("By layer:")
    for lyr in sorted(layer_found):
        f = layer_found[lyr]
        h = layer_hit[lyr]
        if f:
            print(f"  {lyr:22s} {100 * h / f:6.2f}%  ({h}/{f})")
    print()

    # Critical files at 0%.
    critical_zero = []
    for p, (h, _f) in included.items():
        r = rel(p)
        if h == 0 and any(m in r for m in CRITICAL_MARKERS):
            critical_zero.append(r)

    ok = True
    if pct < args.threshold:
        print(f"FAIL: coverage {pct:.2f}% is below threshold "
              f"{args.threshold:.2f}%")
        ok = False
    if critical_zero:
        print("FAIL: critical infrastructure files at 0% coverage:")
        for r in sorted(critical_zero):
            print(f"  - {r}")
        ok = False

    if ok:
        print("PASS: coverage threshold met and no critical file at 0%.")
        return 0
    return 1


if __name__ == "__main__":
    sys.exit(main())
