import 'package:flutter/material.dart';

/// Paths to the brand artwork bundled with the app.
///
/// Everything here is generated by `tool/brand_assets.py` from the masters in
/// `assets/branding`; see `docs/branding.md` for the usage rules.
///
/// Two kinds of asset live in this list, and the difference matters:
///
///  * The **logos** are two-colour (an ink ring plus a terracotta dot), so they
///    ship as a light/dark pair. Pick one with [BrandMarks.forBrightness];
///    tinting them would destroy the two-colour relationship.
///  * The **decoratives** are single-colour alpha masks: the dry-brush texture
///    lives entirely in the alpha channel. Draw them through
///    [BrandMarks.tinted] so one file adapts to any theme colour.
///
/// Only the marks listed here are bundled. `tool/brand_assets.py` also derives
/// a botanical sprig, a milestone burst, a divider and an underline; those stay
/// on disk as a design kit. Adding one back means declaring it in `pubspec.yaml`
/// as well, so nothing ships that no screen draws.
abstract final class BrandAssets {
  static const String _dir = 'assets/branding/derived';

  /// Espresso ensō with a terracotta dot. Light surfaces only.
  static const String logoOnLight =
      '$_dir/budgetsense-logo-primary-on-light.png';

  /// Cream ensō with a terracotta dot. Dark surfaces only.
  static const String logoOnDark = '$_dir/budgetsense-logo-inverse-on-dark.png';

  /// The ensō ring on its own, without the terracotta dot. An even stroke
  /// weight, so it holds up while being revealed, rotated, or faded. Used for
  /// both the loading indicator and the clean-slate empty state.
  static const String ensoRing = '$_dir/budgetsense-enso-ring.png';

  /// Three sweeping ink waves. Drawn once, travelling, when the dashboard is
  /// pulled well past its top.
  static const String waves = '$_dir/budgetsense-waves.png';

  /// Terracotta wax seal. Only where sealing something is the actual meaning:
  /// a completed export or an archived period.
  static const String seal = '$_dir/budgetsense-seal-terracotta.png';
}

/// Helpers for drawing brand artwork against the right background.
abstract final class BrandMarks {
  /// The ensō logo that will actually be visible on [brightness].
  ///
  /// Espresso ink vanishes on an espresso surface and cream ink vanishes on
  /// cream, so this choice is not cosmetic.
  static String forBrightness(Brightness brightness) =>
      brightness == Brightness.dark
          ? BrandAssets.logoOnDark
          : BrandAssets.logoOnLight;

  /// The ensō logo for the current [context]'s theme.
  static String of(BuildContext context) =>
      forBrightness(Theme.of(context).brightness);

  /// Draws a single-colour brand mask in [color].
  ///
  /// Only pass a mask asset (the decoratives, not the logos). [semanticLabel]
  /// stays null for purely decorative marks so screen readers skip them.
  ///
  /// A mark that fails to load draws nothing rather than the framework's error
  /// box. These are decoration, and one missing file (an asset dropped from
  /// `pubspec.yaml`, say) should never put a red rectangle in front of someone
  /// looking at their own money.
  static Widget tinted(
    String asset, {
    required Color color,
    double? size,
    double? width,
    double? height,
    String? semanticLabel,
  }) {
    return Image.asset(
      asset,
      width: width ?? size,
      height: height ?? size,
      color: color,
      colorBlendMode: BlendMode.srcIn,
      fit: BoxFit.contain,
      excludeFromSemantics: semanticLabel == null,
      semanticLabel: semanticLabel,
      errorBuilder: (_, __, ___) => SizedBox(
        width: width ?? size,
        height: height ?? size,
      ),
    );
  }
}
