/// Warm, personal dashboard greetings. Each contains a `{name}` placeholder and
/// a small, friendly emoji. One is shown at the top of the dashboard and a new
/// one is chosen each time the app is opened, so it always feels a little fresh.
library;

/// 100+ greeting variations. `{name}` is replaced with the user's nickname (if
/// set) or first name; when neither exists it gracefully becomes "there".
const List<String> dashboardGreetings = [
  'Hello, {name} 👋',
  'Hey {name}! 😊',
  'Good to see you, {name} 🙂',
  'Welcome back, {name} 🎉',
  'How has the day been so far, {name}? 🌤️',
  'There you are, {name}! ✨',
  'Hi {name}, ready when you are 💪',
  'Look who it is, {name}! 😄',
  'Nice to have you here, {name} 🌸',
  'Hey again, {name} 👀',
  'What a lovely day to check in, {name} ☀️',
  'Hope you\'re smiling today, {name} 😁',
  'Missed you, {name}! 💛',
  'Let\'s make today count, {name} 🚀',
  'Great to see you, {name} 🌟',
  'Howdy, {name}! 🤠',
  'Hey there, money maestro {name} 🎻',
  'Back for more, {name}? Love it 💚',
  'Good vibes only, {name} 🌈',
  'You\'ve got this, {name} 💫',
  'Warm hello to you, {name} 🫖',
  'Hi {name}, your money missed you 💸',
  'Fancy seeing you here, {name} 😉',
  'Rise and shine, {name} 🌅',
  'Evening, {name}. How did today treat you? 🌙',
  'Hey {name}, let\'s peek at the numbers 🔢',
  'So glad you\'re here, {name} 🥰',
  'Hello again, budgeting star {name} ⭐',
  'Sending good energy your way, {name} 🌻',
  'Hi {name}! Small steps, big wins 🐾',
  'Ready to conquer today, {name}? 🏆',
  'Hey {name}, deep breath, you\'re on track 🧘',
  'Cheers to you, {name}! 🥂',
  'Well hello, {name} 🎈',
  'Good to have you back, {name} 🔁',
  'Hi {name}, let\'s keep the streak alive 🔥',
  'Hey {name}, your future self says thanks 🙏',
  'A big hello to {name}! 📣',
  'Hope today\'s been kind, {name} 🍃',
  'Hey {name}, one entry at a time 🧩',
  'Lovely to see you, {name} 🌷',
  'Hi {name}! Today\'s a fresh page 📖',
  'You showed up, {name}. That\'s the win 🎯',
  'Hey {name}, money looks good on you 😎',
  'Welcome, {name}! Let\'s do this 🙌',
  'Hi {name}, staying mindful, one rupee at a time 🪙',
  'Good day, {name}! ☕',
  'Hey {name}, proud of you already 🥳',
  'Here for you, {name} 🤝',
  'Hello sunshine {name} 🌞',
  'Hey {name}, let\'s tidy up those numbers 🧹',
  'Great timing, {name}! ⏰',
  'Hi {name}, calm mind, clear budget 🌊',
  'You again, {name}? Wonderful 💐',
  'Hey {name}, every day you show up matters 📅',
  'Hi {name}, let\'s make money make sense 🧠',
  'Warmest hello, {name} 🔆',
  'Hey {name}, small habits, steady growth 🌱',
  'Look at you go, {name} 🏃',
  'Hi {name}! Keeping it real today 💯',
  'Hey {name}, your goals are getting closer 🎣',
  'Delighted you\'re here, {name} 😌',
  'Hi {name}, let\'s check in gently 🕊️',
  'Hey {name}, today is yours 🗝️',
  'Good to see your face, {name} 😊',
  'Hi {name}! One calm minute for money 🧘‍♀️',
  'Hey {name}, you\'re building something great 🏗️',
  'Hello, wonderful {name} 🌼',
  'Hi {name}, steady as you go 🚶',
  'Hey {name}, numbers are friendlier with you 🤗',
  'Welcome home, {name} 🏡',
  'Hi {name}! Let\'s keep it light and honest 🪶',
  'Hey {name}, another day, another win 🥇',
  'So nice to see you, {name} 💞',
  'Hi {name}, your budget is glad you\'re back 📗',
  'Hey {name}, progress over perfection 📈',
  'Hello, {name}, let\'s take a peek 👓',
  'Hi {name}! Gentle reminder: you\'re doing well 🌿',
  'Hey {name}, money clarity coming right up 🔍',
  'Good to catch you, {name} 🎏',
  'Hi {name}, breathe in, log it out 💨',
  'Hey {name}, you make budgeting look easy 🪄',
  'Hello, {name}! Ready to roll 🎲',
  'Hi {name}, one tap closer to your goals 👆',
  'Hey {name}, staying on top of it, love that 🧗',
  'Welcome back, superstar {name} 🌠',
  'Hi {name}! Let\'s keep things flowing 🌬️',
  'Hey {name}, today\'s numbers await 🔟',
  'Lovely day for a check-in, {name} 🦋',
  'Hi {name}, calm and collected 🧊',
  'Hey {name}, your consistency is inspiring 🌟',
  'Hello, {name}, glad you made time ⌛',
  'Hi {name}! Keep that good momentum 🛼',
  'Hey {name}, mindful money, happy you 🧡',
  'Good to see you again, {name} 🔄',
  'Hi {name}, let\'s make it a good money day 🍀',
  'Hey {name}, you\'re the boss of your budget 👑',
  'Hello there, {name} 💌',
  'Hi {name}! Small wins add up 🧮',
  'Hey {name}, thanks for showing up today 🌇',
  'Welcome, dear {name} 🕯️',
  'Hi {name}, your money journey continues 🧭',
  'Hey {name}, steady hands, steady savings 🤲',
  'Hello, {name}! Let\'s wrap the day nicely 🎁',
  'Hi {name}, you and your goals, together 🫱🫲',
  'Hey {name}, one honest look, that\'s all 👁️',
  'So good to see you, {name} 🌹',
];
